/*
* generated by Xtext
*/
package org.laas.vertics.fiacre;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class LangStandaloneSetup extends LangStandaloneSetupGenerated{

	public static void doSetup() {
		new LangStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

