/*
 * generated by Xtext
 */
package org.laas.vertics.fiacre;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LangRuntimeModule extends org.laas.vertics.fiacre.AbstractLangRuntimeModule {	
}
