/*
 * generated by Xtext
 */
package org.laas.vertics.fiacre.ui.contentassist

import org.laas.vertics.fiacre.ui.contentassist.AbstractLangProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class LangProposalProvider extends AbstractLangProposalProvider {
}
